name: Build Docs w/ Pandoc & Deploy Output to Branch

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Build Docs
        run: docker run --rm --volume $PWD/org.omg.sysml.site:/data --entrypoint "/data/build.sh" pandoc/latex

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          # or github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: org.omg.sysml.site
          publish_dir: ./org.omg.sysml.site
